### ISSUE TITLE
Healing Aura and Blazing Protection collars have odd duplication behaviors when swapped out.

### ISSUE THREAD

**Issue by DoctorWafflePhD** [AlexModGuy/DomesticationInnovation#104]
When Collar Tags enchanted with Healing Aura or Blazing Protection are removed from a pet by giving them a different collar, they behave unusually - the new collar tag that is given is converted to a Healing Aura/Blazing Protection collar. Blazing Protection is weirdly inconsistent, as it only replaces certain enchantments, but Healing Aura will override any collar. See attached videos for examples.

https://user-images.githubusercontent.com/111939112/204674329-13c2b94b-aee1-4104-922b-a359fdb9382b.mp4

(^ Healing Aura ^)

https://user-images.githubusercontent.com/111939112/204674445-f9747555-d671-4e12-be46-5286661a9a38.mp4

(^ Blazing protection ^)

Minecraft version - 1.19.2
FML version - 43.1.53
Citadel version - 2.1.0
Domestication Innovation version - 1.6.0

**Comment by crafting-Aaron** [comment]
Yup. This is still a problem with Healing Aura. At first thought this was enchantment exclusiveness making weird stuff but trying to add Psychic Wall to a collar with Healing Aura will just copy the old tag.
