### ISSUE TITLE
[1.18.2] Random Crash with Dragon Mounts Mod

### ISSUE THREAD

**Issue by Camawama** [AlexModGuy/DomesticationInnovation#127]
Players are crashing on my server with this crash report: 

Appears to have something to do with your mod and Nyf's Spiders mod.

[crash-2023-03-13_22.07.44-client.txt](https://github.com/AlexModGuy/DomesticationInnovation/files/10964367/crash-2023-03-13_22.07.44-client.txt)

**Comment by AlexModGuy** [comment]
dupe #130
