### ISSUE TITLE
Crashing caused by Domestication Enchantment on a Flutter with Nyfs Spiders 2.0 Installed

### ISSUE THREAD

**Issue by MCKuma** [AlexModGuy/DomesticationInnovation#130]
[crash-2023-04-10_13.33.06-server.txt](https://github.com/AlexModGuy/DomesticationInnovation/files/11193488/crash-2023-04-10_13.33.06-server.txt)

Seems to be a bug with Intimidation. Let me know if this is a error on Nyfs side and I can report it there. Thank you.

**Comment by AlexModGuy** [comment]
def not my bug
