### ISSUE TITLE
1.20.1 testing for domesticationinnovation-1.7.0-1.20

### ISSUE THREAD

**Issue by WilliamBlaze** [AlexModGuy/DomesticationInnovation#151]
While i'm still new to the mod itself - it APPEARS to be working as intended during testing in a new creative world in 1.20.1 

I manually added the mod to my 1.20.1's mod folder, figuring since Citadel was already updated to 1.20.1, and that very few drastic change's have been made in the way Minecraft handles its over all coding between 1.20 and 1.20.1 - odds were in favor that this mod would in fact function properly' (ignoring the possibly of minor bugs that have already been submitted by other users)

As i said it appears to be working - Not sure if horses were intentionally suppose to be able to use the pet tags from the mod or if that happened due to creative mode permissions, but it certainly makes this newly changed to skeletal horse look interesting with the way those shadow hands all connected to a shadowy mass inside its ribcage https://media.essential.gg/f2ffa4a6-5220-422e-7fcc-8f9c7ac05400
https://media.essential.gg/92a8d463-9fa5-428c-13fa-d7430a0c8c00
https://media.essential.gg/7a619428-83cf-4a62-49ea-ddd684012500

You can ignore the high HP and levels on these test subjects, that's due to another mod that gives all mobs the ability to level up.

Though i will say i found it an interesting side effect that the dog leveled up from 6 to 7 after applying a pet tag to it. Not sure if that was due to the extra health from Health Boost 3 enchantment that triggered an update on the dog's level or if it was something else entirely. The same thing failed to happen for the horse though when using a matching copy of the same enchanted pet tag that was used on the dog.

That being said it might be worth further testing to see how "Domestication innovation" and the "auto leveling" ( https://www.curseforge.com/minecraft/mc-mods/auto-leveling ) mods interact with each other on the stats changes leveling up might have on tamed animal functions outside of added HP, Armor, attack speed, movement speed, and attack damage all based on tamed pet's level (all mobs affected by auto leveling have increases in these stats by a set amount, increasing with their levels, though I doubt it should have any effect on the functions of Domestication innovations over all.)

Forge Version 47.1.3 for Minecraft 1.20.1 is being used during this testing.

**Comment by Mar-089** [comment]
Ive tried that and Its not working for some odd reason it might be my other mods but I removed them all and kept it and it still didnt work

**Comment by WilliamBlaze** [comment]
yeah that happens to me on occasion too when adding new mods to an existing world, or even when making a new world for the new mods to be tested. - its a forge/minecraft glitch I think'

**Comment by WilliamBlaze** [comment]
Just doing a follow up after multiple months of testing. the results are that it's completely stable with any and all pet mods and functions fully as intended in Minecraft 1.20.1. it even works with mobs added by fabric mods quite nicely in fact. --Well, at least of those few fabric mods that are working on forge thanks to the "Forgified Fabric API" & "Sinytra Connector" mods at anyrate!
