### ISSUE TITLE
cant take off intimidation

### ISSUE THREAD

**Issue by Goatart** [AlexModGuy/DomesticationInnovation#25]
you cant take off Initimidation colar tag of your pet, and when try in survival, the colar tag disappear and the pet continue with Initimidation when are angry

![Cant take off enchantment](https://user-images.githubusercontent.com/103657599/164235665-2894a1b8-cce2-4666-963e-95e900e6b2b2.png)

**Comment by Shibva** [comment]
theres a bug im experincing like this with all tags in 18.2

going to make a separate report
